# Automatically find all .tex files in the current directory
TEX_FILES := $(wildcard *.tex)
PDF_FILES := $(TEX_FILES:.tex=.pdf)

# Default target to build all PDFs
all: $(PDF_FILES)

# Rule to compile .tex files to .pdf
%.pdf: %.tex
	pdflatex -interaction=nonstopmode $<
	pdflatex -interaction=nonstopmode $<
	pdflatex -interaction=nonstopmode $<

# Clean up auxiliary files generated by pdflatex
clean:
	rm -f *.aux *.log *.out *.toc *.synctex.gz *.nav *.snm

# Remove PDFs as well
cleanall: clean
	rm -f $(PDF_FILES)

.PHONY: all clean cleanall

